
SELECT DISTINCT car.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS car, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS hist
WHERE car.CAR_ID = hist.CAR_ID
  AND car.CAR_TYPE LIKE "세단"
  AND START_DATE >= "20221000"
ORDER BY car.CAR_ID DESC