-- 코드를 입력하세요
SELECT car.CAR_ID, car.CAR_TYPE, ROUND(car.DAILY_FEE * 30 * (100-plan.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS car,
  CAR_RENTAL_COMPANY_DISCOUNT_PLAN  AS plan
WHERE car.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '20221101'
      AND START_DATE <= '20221130'
  )
  AND car.CAR_TYPE in ('세단', 'SUV')
  AND plan.CAR_TYPE = car.CAR_TYPE
  AND plan.DURATION_TYPE = '30일 이상'
HAVING FEE >= 500000
  AND FEE < 2000000
ORDER BY FEE DESC, car.CAR_TYPE, car.CAR_ID DESC;
